name: "Copilot Setup Staps"

# Automatically run the setup staps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-staps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-staps.yml

jobs:
  # The job MUST be called `copilot-setup-staps` or it will not be picked up by Copilot.
  copilot-setup-staps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your staps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup staps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup staps, Copilot will do this for you automatically after the staps complete.
      contents: read

    # You can define any staps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    staps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci
